# Salary Statistics Analyzer

## Objective

Analyze employee salary data using statistical methods.

## Statistical Concepts

- Mean
- Median
- Mode
- Variance
- Standard Deviation
- Z-score
- Covariance
- Correlation
- Probability
- Bayes' Theorem
- Confidence Interval
- Hypothesis Testing
- Normalization
- Standardization

In [34]:
import numpy as np
import pandas as pd
import plotly.express as px
from scipy import stats
import os
from sklearn.preprocessing import MinMaxScaler, StandardScaler
print("Libraries are successfully imported")

Libraries are successfully imported

## 1. Load Dataset

In [35]:
df= pd.read_csv("dataset.csv")
os.makedirs("./outputs", exist_ok=True)

## 2. Info about dataset

In [36]:
df.shape
df.info()
df.describe()
df.isna().sum()
df.duplicated().sum()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  5 non-null      str
 1   age          5 non-null      int64
 2   experience   5 non-null      int64
 3   education    5 non-null      str
 4   job_role     5 non-null      str
 5   salary       5 non-null      int64
dtypes: int64(3), str(3)
memory usage: 494.0 bytes

np.int64(0)

## 3. Basic salary statistics

In [37]:
mean_salary= df["salary"].mean()
print("Mean Salary: ", mean_salary)

median_salary= df["salary"].median()
print("Median Salary: ", median_salary)

mode_salary= df["salary"].mode()
print("Mode Salary: ", mode_salary)

variance_salary= df["salary"].var()
print("Salary Variance: ", variance_salary)

standard_salary= df["salary"].std()
print("Standard Salary: ", standard_salary)

Mean Salary:  59400.0
Median Salary:  55000.0
Mode Salary:  0    35000
1    42000
2    55000
3    70000
4    95000
Name: salary, dtype: int64
Salary Variance:  574300000.0
Standard Salary:  23964.55716260995

## 4. Salary Stats

In [38]:
salary_stats = {
    "Mean": df["salary"].mean(),
    "Median": df["salary"].median(),
    "Mode": df["salary"].mode(),
    "Variance": df["salary"].var(),
    "Std": df["salary"].std(),
}
salary_stats

{'Mean': np.float64(59400.0),
 'Median': np.float64(55000.0),
 'Mode': 0    35000
 1    42000
 2    55000
 3    70000
 4    95000
 Name: salary, dtype: int64,
 'Variance': np.float64(574300000.0),
 'Std': np.float64(23964.55716260995)}

## 4. Salary Distribution

In [39]:
fig= px.histogram(
    df,
    x= "salary",
    nbins=5,
    title="Salary Distribution"
)

fig.show()
fig.write_image("./outputs/salary_distribution.png")

## 5. Salary by experience

In [40]:
fig= px.scatter(
    df,
    x="experience",
    y="salary",
    title="Experience vs Salary"
)
fig.show()
fig.write_image("./outputs/Experience_vs_Salary.png")
correlation= df["experience"].corr(df["salary"])
print(f"Experience-Salary Correlation: ", correlation)
numeric_df = df[["age", "experience", "salary"]]
correlation_matrix = numeric_df.corr()
fig= px.imshow(
    correlation_matrix,
    title="Correlation Matrix"
)
fig.show()
fig.write_image("./outputs/correlation_matrix.png")

Experience-Salary Correlation:  0.9995543855214601

## 6. Calculate Z-score for Salary

In [41]:
df["salary_zscore"]= stats.zscore(df["salary"])
df[["salary", "salary_zscore"]]
fig= px.bar(
    df,
    x="salary",
    y="salary_zscore",
    title="Zscore calculation of salary"
)
fig.show()
fig.write_image("./outputs/zScore_for_salary.png")

## 7. Outliers

In [42]:
outliers= df[abs(df["salary_zscore"])>3]
outlier_count= (abs(df["salary_zscore"])>3).sum()
print("Nummber of Salary Outliers: ", outlier_count)
df["salary_outlier"]= abs(df["salary_zscore"])>3
df[["employee_id", "salary", "salary_zscore", "salary_outlier"]]
fig= px.box(
    df,
    y="salary",
    title="Salary Boxplot"
)
fig.show()
fig.write_image("./outputs/salary_boxplot.png")

Nummber of Salary Outliers:  0

## 8. Calculating covariance

In [43]:
# cov_exp_salary= df["experience"].cov(df["salary"])
cov_exp_salary= df[["experience", "salary"]].cov()
cov_exp_salary

            experience       salary
experience        12.8      85700.0
salary         85700.0  574300000.0

## 9. Calculate Probability

In [44]:
total_emp= len(df)
print("Total Employees: ", total_emp)
high_salary_count=(df["salary"]>60000).sum()
print("Employees earning more than 60000: ", high_salary_count)
probability_high_salary= high_salary_count/total_emp
print(f"Probability of random selecting an employee earning more than 60000: ", probability_high_salary)

salary_range=(
    (df["salary"]>=40000) & 
    (df["salary"]<=70000)
)
range_count= salary_range.sum()
probability_range= range_count/len(df)
print( f"Probability of salary between 40000 and 70000: "
    f"{probability_range:.2%}")

experienced= df["experience"]>5
probability_experienced= experienced.mean()
print(
    f"Probability of experience > 5 years: "
    f"{probability_experienced:.2%}"
)
high_salary_given_experience=(
    (df["salary"]>60000) & experienced
).sum()

Total Employees:  5
Employees earning more than 60000:  2
Probability of random selecting an employee earning more than 60000:  0.4
Probability of salary between 40000 and 70000: 60.00%
Probability of experience > 5 years: 40.00%

## 10. Calculate Conditional Proababilty

In [45]:
experienced_count= experienced.sum()
conditional_probability=(
    high_salary_given_experience/experienced_count
)
print(
    "P(Salary > 60000 | Experience > 5):",
    conditional_probability
)

print(
    f"Percentage: {conditional_probability:.2%}"
)

P(Salary > 60000 | Experience > 5): 1.0
Percentage: 100.00%

## 11. Likelihood

In [46]:
high_salary=df["salary"]>60000
p_experienced_given_high_salary=(
    (experienced & high_salary).sum()/high_salary.sum()
)
print(f"P(Experienced | High Salary) = {p_experienced_given_high_salary}")

p_high_salary_given_experienced=(
    p_experienced_given_high_salary*high_salary/experienced
)
print(f"P(High Salary | Experienced) = {p_high_salary_given_experienced}")

P(Experienced | High Salary) = 1.0
P(High Salary | Experienced) = 0    NaN
1    NaN
2    NaN
3    1.0
4    1.0
dtype: float64

## 12. Confidence interval

In [47]:
sample_mean= df["salary"].mean()
sample_std= df["salary"].std()
sample_size= df["salary"].count()

std_error= sample_std/ np.sqrt(sample_size)

confidence_interval= stats.t.interval(
    confidence=0.95,
    df= sample_size -1,
    loc= sample_mean,
    scale= std_error
)
lower_bound, upper_bound= confidence_interval
print(f" Sample Mean: {sample_mean}")
print(f"95% confidence interval: {lower_bound}, {upper_bound}")

 Sample Mean: 59400.0
95% confidence interval: 29644.072138291078, 89155.92786170891

## 13. Interpretation

In [48]:
import plotly.graph_objects as go

# Display results
print(f"Mean Salary:  {sample_mean:,.2f}")
print(f"Lower Bound:  {lower_bound:,.2f}")
print(f"Upper Bound:  {upper_bound:,.2f}")

# Create figure
fig = go.Figure()

# Add mean salary with confidence interval
fig.add_trace(
    go.Scatter(
        x=["Mean Salary"],
        y=[sample_mean],
        mode="markers",
        marker=dict(size=12),
        error_y=dict(
            type="data",
            symmetric=False,
            array=[upper_bound - sample_mean],
            arrayminus=[sample_mean - lower_bound],
            visible=True,
            thickness=2,
            width=8
        ),
        hovertemplate=(
            "Mean Salary: %{y:,.2f}<br>"
            f"95% CI: {lower_bound:,.2f} – {upper_bound:,.2f}"
            "<extra></extra>"
        )
    )
)

# Customize layout
fig.update_layout(
    title="95% Confidence Interval for Mean Salary",
    xaxis_title="",
    yaxis_title="Salary",
    template="plotly_white",
    width=800,
    height=500
)

# Display
fig.show()

Mean Salary:  59,400.00
Lower Bound:  29,644.07
Upper Bound:  89,155.93

## 14. Hypothesis Testing

In [49]:
hypothesized_mean= 60000
alpha= 0.05
t_statistic, p_value= stats.ttest_1samp(
    df["salary"],
    hypothesized_mean
)
print(f"Sample Mean: {df['salary'].mean():,.2f}")
print(f"Hypothesized Mean: {hypothesized_mean:,.2f}")
print(f"T-statistic: {t_statistic:.4f}")
print(f"P-value: {p_value:.4f}")
if p_value< alpha:
    print("Decision: Reject the null hypothesis")
    print(
        "There is statistically significant evidence that "
        "the mean salary differs from 60000."
    )
else:
    print("Decision: Fail to Reject the Null Hypothesis")
    print(
        "There is not enough statistical evidence to conclude "
        "that the mean salary differs from 60000."
    )

Sample Mean: 59,400.00
Hypothesized Mean: 60,000.00
T-statistic: -0.0560
P-value: 0.9580
Decision: Fail to Reject the Null Hypothesis
There is not enough statistical evidence to conclude that the mean salary differs from 60000.

## 15. Normalization

In [50]:
df["salary_normalized"]=MinMaxScaler().fit_transform(
    df[["salary"]]
)
df[["salary", "salary_normalized"]].head()
print(df[["salary", "salary_normalized"]].head())
print(f"Minimum Normalized Salary: ", df["salary_normalized"].min())
print(f"Maximum Normalized Salary: ", df["salary_normalized"].max())

#multiple features normalization
features= df[
    ["age", "experience", "salary"]
].copy()
normalize_data= MinMaxScaler().fit_transform(features)

normalize_df= pd.DataFrame(
    normalize_data,
    columns=features.columns
)
normalize_df.head()

fig= px.imshow(
    normalize_df,
    title="Normalized features ranges 0-1"
)
fig.show()
fig.write_image("./outputs/normalized_featiures.png")

   salary  salary_normalized
0   35000           0.000000
1   42000           0.116667
2   55000           0.333333
3   70000           0.583333
4   95000           1.000000
Minimum Normalized Salary:  0.0
Maximum Normalized Salary:  1.0

## 16. Standardization

In [51]:
df["salary_standarized"]= StandardScaler().fit_transform(
    df[["salary"]]
)
df[["salary", "salary_standarized"]].head()
print(df[["salary", "salary_standarized"]].head())
print("Mean: ", df["salary_standarized"].mean())
print("STD: ", df["salary_standarized"].std())

#multiple features standarization
standardized_data=StandardScaler().fit_transform(
    features
)
standardized_df= pd.DataFrame(
    standardized_data, 
    columns=features.columns
)
standardized_df.head()

   salary  salary_standarized
0   35000           -1.138349
1   42000           -0.811773
2   55000           -0.205276
3   70000            0.494529
4   95000            1.660870
Mean:  0.0
STD:  1.118033988749895

        age  experience    salary
0 -1.355262     -1.1250 -1.138349
1 -0.677631     -0.8125 -0.811773
2  0.000000     -0.1875 -0.205276
3  0.451754      0.4375  0.494529
4  1.581139      1.6875  1.660870

## 17. Final Summary

In [53]:
final_summary={
     "Mean Salary": df["salary"].mean(),
    "Median Salary": df["salary"].median(),
    "Mode Salary": df["salary"].mode().iloc[0],
    "Variance": df["salary"].var(),
    "Standard Deviation": df["salary"].std(),
    "Minimum Salary": df["salary"].min(),
    "Maximum Salary": df["salary"].max(),
    "Experience-Salary Correlation":
        df["experience"].corr(df["salary"]),
    "P(Salary > 60000)":
        (df["salary"] > 60000).mean(),
    "P(Experience > 5)":
        (df["experience"] > 5).mean()
}
summary_df= pd.DataFrame(
    final_summary.items(),
    columns=["Metric", "Value"]
)
summary_df
fig= px.histogram(
    df,
    x="salary",
    title="Salary Dist"
)
fig.show()